version: '3.7'
services:
    sonarqube:
        image: sonarqube:8.3.1-community
        container_name: sonarqube
        hostname: sonarqube
        restart: unless-stopped
        ports:
            - "9000:9000"
        networks:
            - sonarnet
#        command: -Dsonar.web.context=/sonarqube
#        environment:
#            - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonar
#            - sonar.jdbc.username=sonar
#            - sonar.jdbc.url=sonar
#        volumes:
#            - sonarqube_conf:/opt/sonarqube/conf
#            - sonarqube_data:/opt/sonarqube/data
#            - sonarqube_extensions:/opt/sonarqube/extensions
#            - sonarqube_bundled_plugins:/opt/sonarqube/lib/bundled-plugins

#    postgres:
#        image: postgres:12.2
#        container_name: postgres
#        hostname: postgres
#        restart: unless-stopped
#        networks:
#            - sonarnet
#        ports:
#            - "5432:5432"
#        environment:
#            - POSTGRES_USER=sonar
#            - POSTGRES_PASSWORD=sonar
#            - POSTGRES_DB=sonar
#        volumes:
#            - postgresql:/var/lib/postgresql
#            - postgresql_data:/var/lib/postgresql/data

#volumes:
#    sonarqube_conf:
#    sonarqube_data:
#    sonarqube_extensions:
#    sonarqube_bundled_plugins:
#    postgresql:
#    postgresql_data:

networks:
    sonarnet:
        driver: bridge
